### ISSUE TITLE
New action name is... "service"

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-service#103]
Run `npm init @adobe/helix-service` and fill with wizard with "dummy" (to generate a helix-dummy service).
Run `npm run deploy`

-> the generated action is `service`: `"https://adobeioruntime.net/api/v1/web/acapt/helix-services-private/service@1.4.9`

Expect: action name is `helix-dummy` like everything else.

**Comment by trieloff** [comment]
In `package.json`:

```json
"wsk": {
    "name": "helix-services-private/service@${version}",
    "linksPackage": "helix-services"
  },
```
