### ISSUE TITLE
Error on new template creatino

### ISSUE THREAD

**Issue by swarali** [adobe/helix-service#93]
**Error message**
(node:5954) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/swarali/.npm/_npx/5826/lib/node_modules/@adobe/create-helix-service/template/dot-eslintignore'
(node:5954) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5954) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tripodsan** [comment]
we need to rename all `.` files in template like in: https://github.com/adobe/helix-library/tree/master/template
